name: merge master to live
run-name: merge master to live
on: workflow_dispatch
jobs:
  merge-master-to-live:
      runs-on: ubuntu-latest
      steps:
        - name: checkout-master
          uses: actions/checkout@v4.1.7
          with:
            ref: master
  
        - name: merge-to-live
          uses: everlytic/branch-merge@1.1.2
          with:
            github_token: ${{ secrets.github_token }}
            source_ref: 'master'
            target_branch: 'dist'
            commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
